### ISSUE TITLE
Error while trying to require('ibm-whcs-services/annotator-for-clinical-data/v1') 

### ISSUE THREAD

**Issue by Haroon-KA** [IBM/whcs-node-sdk#19]
Bug description: 
The nodejs sdk initialization fails throwing the error 
`Error: Cannot find module 'ibm-whcs-services/annotator-for-clinical-data/v1'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/ubuntu/NLP/ibm_acd/app.js:1:39)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)`

The service import path mentioned in the github README is not present.
![ibm_node_sdk issue](https://user-images.githubusercontent.com/15683388/94152254-fceb8900-fe98-11ea-93f9-06c6a024cbc6.PNG)

There is a mismatch in the project name and library name  whcs-node-sdk vs ibm-whcs-sdk

Steps to Reproduce: 
Step 1: 
Follow the steps mentioned in the IBM ACD node sdk documentation [IBM Cloud API Docs/Annotator For Clinical Data](https://cloud.ibm.com/apidocs/wh-acd?code=node#introduction).
The npm install fails throwing : 
`npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/whcs-node-sdk - Not found
npm ERR! 404 
npm ERR! 404  'whcs-node-sdk@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2020-09-24T13_22_48_628Z-debug.log
`
Step 1 error resolution: The package name mentioned in the official IBM documentation is 'npm install whcs-node-sdk' whereas the actual package name is 'ibm-whcs-sdk'. Hence perform 'npm install ibm-whcs-sdk'

Now on trying to require require('ibm-whcs-services/annotator-for-clinical-data/v1') throw the aforementioned error 'Error: Cannot find module 'ibm-whcs-services/annotator-for-clinical-data/v1' . 

Expectation: 
The annotator-for-clinical-data/v1 module should have been loaded. The actual service path for the annotator-for-clinical-data/v1 module is 'ibm-whcs-sdk/annotator-for-clinical-data/v1' and the same is applicable for 'insights-for-medical-literature/v1' as well i.e ('ibm-whcs-sdk/insights-for-medical-literature/v1')

**Screenshots**

**Must gather (please complete the following information):**
 - SDK Version -0.1.0
 - Node Version >10
 - Name of service that you're trying to use (if applicable) - annotator-for-clinical-data and insights-for-medical-literature
 - Name of operation that you're trying to invoke (if applicable) - requiring modules annotator-for-clinical-data and insights-for-medical-literature

**Comment by dcwebermn** [comment]
The Readme was updated to reflect the proper bundle name.
npm install ibm-whcs-sdk
